### ISSUE TITLE
Faulty analysis results

### ISSUE THREAD

**Issue by ragnarkurm** [klausi/drupalpractice#1]
I'm having following function:

    public function getKeys() {

      switch ($this->field_type) {
        case 'number_decimal':
    116   return array(
            'delta' => new DrushFieldsGetFormatterDelta(),
            'dec' => new DrushFieldsGetFormatterValue(dt('Decimal'), dt('Decimal value.')),
          );

        case 'number_float':
    123   return array(
            'delta' => new DrushFieldsGetFormatterDelta(),
            'float' => new DrushFieldsGetFormatterValue(dt('Float'), dt('Floating-point value.')),
          );

        case 'number_integer':
          return array(
            'delta' => new DrushFieldsGetFormatterDelta(),
            'int' => new DrushFieldsGetFormatterValue(dt('Integer'), dt('Integer value.')),
          );
      }

    }

And no matter what I get following results:

116 | ERROR | Case breaking statements must be followed by a single blank line
123 | ERROR | Case breaking statements must be followed by a single blank line

However, this helps:

        $ret = array(
          'delta' => new DrushFieldsGetFormatterDelta(),
          'dec' => new DrushFieldsGetFormatterValue(dt('Decimal'), dt('Decimal value.')),
        );
        return $ret;

**Comment by klausi** [comment]
This project is deprecated because DrupalPractice is now part of Coder.
