### ISSUE TITLE
Documentation Suggestion - Related to "Drupal" Standard

### ISSUE THREAD

**Issue by aglynn** [klausi/drupalpractice#3]
First off, thanks for the fantastic libraries. Next, I wanted to let you know of one point that I think would have helped me with getting up and running that might help someone in the future if they knew it. As background, I am using Linux.

I used Composer to install Code Sniffer (https://www.drupal.org/node/1419988), which you had linked to. I kept getting an error when I tried running it until I added a symlink for the Drupal sniffer:

 sudo ln -sv ~/.composer/vendor/drupal/coder/coder_sniffer/Drupal/ ~/.composer/vendor/squizlabs/php_codesniffer/CodeSniffer/Standards/

Then the following worked fine:
 phpcs --standard=DrupalPractice -- /path/to/my/module/or/theme/or/profile

The error I was getting before adding this symlink was the following: 
phpcs --standard=DrupalPractice -- /path/to/module
PHP Fatal error:  Uncaught exception 'PHP_CodeSniffer_Exception' with message 'Referenced sniff "Drupal.Semantics.FunctionCall" does not exist' in /home/vagrant/.composer/vendor/squizlabs/php_codesniffer/CodeSniffer.php:858
Stack trace:
#0 /home/vagrant/.composer/vendor/squizlabs/php_codesniffer/CodeSniffer.php(587): PHP_CodeSniffer->_expandRulesetReference(Object(SimpleXMLElement), '/vagrant/drupal...', 0)
#1 /home/vagrant/.composer/vendor/squizlabs/php_codesniffer/CodeSniffer.php(435): PHP_CodeSniffer->processRuleset('/vagrant/drupal...')
#2 /home/vagrant/.composer/vendor/squizlabs/php_codesniffer/CodeSniffer/CLI.php(622): PHP_CodeSniffer->process(Array, Array, Array, false)
#3 /home/vagrant/.composer/vendor/squizlabs/php_codesniffer/scripts/phpcs(37): PHP_CodeSniffer_CLI->process()
#4 {main}
  thrown in /home/vagrant/.composer/vendor/squizlabs/php_codesniffer/CodeSniffer.php on line 858

So even though this is an oversight in the Code Sniffer installation instructions, since it only affected my ability to use DrupalPractice (and not DrupalSecure or just the Drupal standards), I am mentioning it here.

**Comment by uberhacker** [comment]
Nice find Anthony.  This also works in Mac OSX if you add Drupal to the end of the symlink command:

sudo ln -sv ~/.composer/vendor/drupal/coder/coder_sniffer/Drupal/ ~/.composer/vendor/squizlabs/php_codesniffer/CodeSniffer/Standards/Drupal

**Comment by klausi** [comment]
This project is deprecated because DrupalPractice is now part of Coder.
